//============================================================================
/// \addtogroup g_applib
/// \{
/// \file
/// Contains the application library interface definition.
//
// Copyright      : GNU General Public License (GPL) Version 3
//============================================================================
#if !defined(APPLIB_H)
#define APPLIB_H

#include <QString>

/// Provide version information generated by the build process.
/// This class provides access to the build and version information
/// generated automatically during the build process.
class VersionInfo
{
    public:
        static QString getVersion();    ///< Get the version provided by git.
        static QString getBuildTag();   ///< Get the build tag provided by jenkins.

    private:
        static const QString buildTag;
        static const QString version;
};

#endif

/// \}  // end of g_applib
